language: objective-c
notifications:
  email: false
  slack: popcorntimetv:7ipJqXmdGZ5u3zm9VkOZiHIV
osx_image: xcode7.3

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=PopcornTime.xcworkspace
    - IOS_SDK=iphonesimulator9.3
  matrix:
    - SCHEME="PopcornTime"      DESTINATION="platform=iOS Simulator,OS=9.3,name=iPhone 6s"      SDK="$IOS_SDK"     RUN_TESTS="NO"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [$RUN_TESTS == "YES"]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi
